#!/usr/bin/env bash

status=$(playerctl status 2>/dev/null)
artist=$(playerctl metadata artist 2>/dev/null)
title=$(playerctl metadata title 2>/dev/null)
album=$(playerctl metadata album 2>/dev/null)
arturl=$(playerctl metadata mpris:artUrl 2>/dev/null)

jq -n \
  --arg status "$status" \
  --arg artist "$artist" \
  --arg title "$title" \
  --arg album "$album" \
  --arg art "$arturl" \
  '{
      status: $status,
      artist: $artist,
      title: $title,
      album: $album,
      art: $art
  }'
